export const OPEN_SIDEBAR = "OPEN_SIDEBAR";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";

export const OPEN_OVERLAY = "OPEN_OVERLAY";
export const CLOSE_OVERLAY = "CLOSE_OVERLAY";

export const CLICK_ON_OVERLAY = "CLICK_ON_OVERLAY";

export const OPEN_CART = "OPEN_CART";
export const CLOSE_CART = "CLOSE_CART";

export const AUTH_WAITING = "AUTH_WAITING";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const AUTH_STOP_LOADING = "AUTH_STOP_LOADING";

export const BRAND_WAITING = "BRAND_WAITING";
export const BRAND_SUCCESS = "BRAND_SUCCESS";
export const BRAND_STOP_LOADING = "BRAND_STOP_LOADING";
export const BRAND_FETCH_SUCCESS = "BRAND_FETCH_SUCCESS";

export const FILTER_SET_GENDER = "FILTER_SET_GENDER";
export const FILTER_SET_BRAND = "FILTER_SET_BRAND";
export const FILTER_RESET = "FILTER_RESET";
export const FILTER_SEARCH = "FILTER_SEARCH";
export const FILTER = "FILTER";

export const CART_WAITING = "CART_WAITING";
export const CART_STOP_LOADING = "CART_STOP_LOADING";
export const CART_FETCH_SUCCESS = "CART_FETCH_SUCCESS";
export const CART_UPDATE_QUANTITY = "CART_UPDATE_QUANTITY";

export const ORDER_SET_INFO = "ORDER_SET_INFO";
